### PR TITLE
use multistage builds and build inside a container

### PR DESCRIPTION
**Pull request by krasi-georgiev**
added a make file to build and push the image
the dockerfile is refactored to use multi stage builds

Signed-off-by: Krasi Georgiev <kgeorgie@redhat.com>

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/alertmanager-github-receiver/17)

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
thanks , updated

**Comment by krasi-georgiev** [comment]
yes you are right , I tested it locally and works as expected.

updated.

**Comment by stephen-soltesz** [comment]
@krasi-georgiev Ah, the travis build is failing -- and it appears that by adding the `Makefile` the implicit step that travis used to take is now skipped. https://docs.travis-ci.com/user/languages/go/#dependency-management

To fix the travis build, please add a new section to .travis.yml (between before_install and go_import_path) like:
```
install:
- go get -t ./...
```

Once the build passes, I'll merge.

**Comment by krasi-georgiev** [comment]
I was wondering about this fail as well. thanks for the pointers.

**Pull request merged**
