### PR TITLE
Enable routing alerts to multiple repos

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/alertmanager-github-receiver/10)

### CODE REVIEW

**Comment by gfr10598** [comment]
Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---

*[issues/handler.go, line 49 at r2](https://reviewable.io/reviews/m-lab/alertmanager-github-receiver/10#-LEMPos8CgSw0yxbCDwJ:-LEMPos8CgSw0yxbCDwK:bnfl2o6) ([raw file](https://github.com/m-lab/alertmanager-github-receiver/blob/2d5abfc7f294fd158e1a97de7218fc84a7b08766/issues/handler.go#L49)):*
> ```Go
> // ListHandler contains data needed for HTTP handlers.
> type ListHandler struct {
> 	Client ListClient
> ```

Can this be embedded instead of explicit?

---

*[issues/handler_test.go, line 63 at r2](https://reviewable.io/reviews/m-lab/alertmanager-github-receiver/10#-LEMPwKw7Vz0LKlyRNPA:-LEMPwKw7Vz0LKlyRNPB:bopi0ge) ([raw file](https://github.com/m-lab/alertmanager-github-receiver/blob/2d5abfc7f294fd158e1a97de7218fc84a7b08766/issues/handler_test.go#L63)):*
> ```Go
> 
> 	// Run the list handler.
> 	handler := issues.ListHandler{
> ```

Maybe keep on one line?

---

*[issues/issues.go, line 80 at r2](https://reviewable.io/reviews/m-lab/alertmanager-github-receiver/10#-LEMQKNB-6ehpM7sghOJ:-LEMQKNB-6ehpM7sghOK:b3kcy73) ([raw file](https://github.com/m-lab/alertmanager-github-receiver/blob/2d5abfc7f294fd158e1a97de7218fc84a7b08766/issues/issues.go#L80)):*
> ```Go
> // ListOpenIssues returns open alert issues in the configured organization.
> // Issues are collected using the Github Search API, so the github.Issues
> // objects return contain partial information.
> ```

I can't parse this sentence.  Syntax error?

---

*[issues/issues.go, line 94 at r2](https://reviewable.io/reviews/m-lab/alertmanager-github-receiver/10#-LEMQajF4TKwDdHD7jDI:-LEMQajF4TKwDdHD7jDJ:b1gdzyv) ([raw file](https://github.com/m-lab/alertmanager-github-receiver/blob/2d5abfc7f294fd158e1a97de7218fc84a7b08766/issues/issues.go#L94)):*
> ```Go
> 		// The search depends on all relevant issues including the "alert:boom:" label.
> 		issues, resp, err := c.GithubClient.Search.Issues(
> 			context.Background(), `is:issue in:title is:open org:`+c.org+` label:"alert:boom:"`, sopts)
> ```

I was just bitten by a context without deadline, so consider adding a deadline/timeout.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/alertmanager-github-receiver/10)*

**Comment by gfr10598** [comment]
:lgtm:
A few nits, but nothing I need to see again.

---

Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/alertmanager-github-receiver/10#-:-LEMRCF-8_hADn7BuH2h:b3xs1kd)*

**Comment by stephen-soltesz** [comment]
Thank you!

---

Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[issues/handler.go, line 49 at r2](https://reviewable.io/reviews/m-lab/alertmanager-github-receiver/10#-LEMPos8CgSw0yxbCDwJ:-LEMlcQtDXEBB-3qm3hv:bcvjgzp) ([raw file](https://github.com/m-lab/alertmanager-github-receiver/blob/2d5abfc7f294fd158e1a97de7218fc84a7b08766/issues/handler.go#L49)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Can this be embedded instead of explicit?
</blockquote></details>

Good idea. Done.

---

*[issues/handler_test.go, line 63 at r2](https://reviewable.io/reviews/m-lab/alertmanager-github-receiver/10#-LEMPwKw7Vz0LKlyRNPA:-LEMlxT7CLTZ0drrXj1C:b-896fix) ([raw file](https://github.com/m-lab/alertmanager-github-receiver/blob/2d5abfc7f294fd158e1a97de7218fc84a7b08766/issues/handler_test.go#L63)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Maybe keep on one line?
</blockquote></details>

Done.

---

*[issues/issues.go, line 80 at r2](https://reviewable.io/reviews/m-lab/alertmanager-github-receiver/10#-LEMQKNB-6ehpM7sghOJ:-LEMwwANDa3PCCzOKqVo:b-1n7cpt) ([raw file](https://github.com/m-lab/alertmanager-github-receiver/blob/2d5abfc7f294fd158e1a97de7218fc84a7b08766/issues/issues.go#L80)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I can't parse this sentence.  Syntax error?
</blockquote></details>

I've tried rephrasing. 

---

*[issues/issues.go, line 94 at r2](https://reviewable.io/reviews/m-lab/alertmanager-github-receiver/10#-LEMQajF4TKwDdHD7jDI:-LEMve4085G16i_rHAd5:bcvjgzp) ([raw file](https://github.com/m-lab/alertmanager-github-receiver/blob/2d5abfc7f294fd158e1a97de7218fc84a7b08766/issues/issues.go#L94)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I was just bitten by a context without deadline, so consider adding a deadline/timeout.
</blockquote></details>

Good idea. Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/alertmanager-github-receiver/10#-:-LEN--j2EWwggh7d2tOL:b-9755fn)*

**Comment by stephen-soltesz** [comment]
https://github.com/m-lab/alertmanager-github-receiver/issues/4

**Pull request merged**
